name: lede全新官方openwrt(自用)
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
jobs:
  Ubuntu:
    runs-on: Ubuntu-20.04
    steps:
    - name: 安装依赖包
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
    - name: 拉取lede-openwrt源码
      run: |
        git clone https://github.com/coolsnowwolf/lede
        cd openwrt
        sed -i '$a src-git lienol https://github.com/MrH723/openwrt-packages' feeds.conf.default
        sed -i 's/192.168.1.1/10.0.0.1/g' package/base-files/files/bin/config_generate
        sed -i "s/OpenWrt /This firmware was compiled by ChenZhilong on $(TZ=UTC-8 date "+%Y.%m.%d") @ OpenWrt /g" package/lean/default-settings/files/zzz-default-settings
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
    - name: 下载dl库
      run: |
        cd openwrt && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: 编译openwrt
      run: |
        cd openwrt
        make -j1 V=s
    - name : 上传openwrt到Actions
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
